### ISSUE TITLE
Badly optimized regex for unoptimized values in the range 81 to 89

### ISSUE THREAD

**Issue by iTob191** [n1klas4008/poe-regex#47]
Selecting for example `89` as quantity and unchecking "Optimize Quantity value" produces the following regex:
```
"m q.*(8[9-9]|[9-9].|1..)%"
```
Both occurrences of `[9-9]` can be simplified to just `9`.

And btw, great tool, thanks for your work!

**Comment by n1klas4008** [comment]
was just adding buttons to land on this issue page and saw this, added this with commit 346de6c42083f66b84db5f135a2d10b7559cd199 on the dev branch, will go live soon

**Comment by n1klas4008** [comment]
optimized with #48 thanks for the feedback!
