### ISSUE TITLE
collateral damage

### ISSUE THREAD

**Issue by potato404** [n1klas4008/poe-regex#52]
my regex is "!t \d+|se a|ns d|olati|xa|s u|ot r|ss r|ur p"

the mods selected are 

- Area contains Drowning Orbs
- Area contains Runes of the Searing Exarch
- Area contains Unstable Tentacle Fiends
- Area contains Awakeners' Desolation
- players and their minions deal no damage 3 out of 10 seconds
- players are targeted by a meteor when they use a flask
- rare monsters have volatile cores
- monsters reflect ele dmg
- monsters reflect phys dmg
- players have reduced effect of auras
- players can not regen life mana or energy shield
- players have less recovery rate of life and energy shield
- players have reduced armour and block 

none of the mods selected are on this map and it is not highlighted 

Item Class: Maps
Rarity: Rare
Filthy Cradle
Sanctuary Map
--------
Map Tier: 17
Item Quantity: +148% (augmented)
Item Rarity: +107% (augmented)
Monster Pack Size: +37% (augmented)
More Maps: +160% (augmented)
More Scarabs: +103% (augmented)
Quality: +20% (augmented)
--------
Item Level: 83
--------
Monster Level: 84
--------
{ Prefix Modifier "Parasitic" (Tier: 1) }
15% of Damage Players' Totems take from Hits is taken from their Summoner's Life instead
{ Prefix Modifier "Savage" (Tier: 1) }
36(30-40)% increased Monster Damage
{ Prefix Modifier "Grasping" (Tier: 1) }
Monsters inflict 2 Grasping Vines on Hit
(Up to 10 Vines can grasp you, inflicting 8% less Movement Speed per Vine. Broken by moving)
{ Suffix Modifier "of Frenzy" (Tier: 1) }
Monsters have +1 to Maximum Frenzy Charges
Monsters gain a Frenzy Charge on Hit
{ Suffix Modifier "of Endurance" (Tier: 1) }
Monsters have +1 to Maximum Endurance Charges
Monsters gain an Endurance Charge when hit
{ Suffix Modifier "of Miring" (Tier: 1) }
Players have 28(30-25)% less Defences
(Armour, Evasion Rating and Energy Shield are the standard Defences)
--------
Travel to this Map by using it in a personal Map Device. Maps can only be used once.
--------
Modifiable only with Chaos Orbs, Vaal Orbs, Delirium Orbs and Chisels
![image](https://github.com/user-attachments/assets/41149d90-7b6e-4aa2-bcf5-89d423e1c8fb)

**Comment by n1klas4008** [comment]
thanks for the report, I will take a look at this later tonight and report back when I know more

**Comment by n1klas4008** [comment]
same issue as mentioned in #54 actually, I have fixed this with #55 - the issue here was that one of the mods you selected spans across more than one line which I did not account for before - it should work as expected now, if you select the same mods you should get a slightly different regex
