### ISSUE TITLE
Generated string for "Players have less armour/chance to block" does not exclude mod

### ISSUE THREAD

**Issue by levlazarev** [n1klas4008/poe-regex#54]
**Describe the bug**
Selected the "Players have #% less Armour Players have #% reduced Chance to Block" modifier in the exclude list but the generated regex did not exclude that mod.

**To Reproduce**
Selected a quantity threshold
Selected mods that I wished to exclude
Copied regex "!se a|ra c|re a|n,|xa|wak|wni|ur p" "m q.*\d{3}%" to clipboard
Pasted into poe search window

**Expected behavior**
Regex that excludes selected mods to exclude all instances of the selected exclusions.

**Screenshots**

Images of selected configuration as well as the string generated.
![image](https://github.com/user-attachments/assets/1d73d82b-3d3a-406e-89c2-72c2d1e3bb5d)
![image](https://github.com/user-attachments/assets/572e8a30-9d0f-4362-91a1-e284e4a8c4a2)
![image](https://github.com/user-attachments/assets/32ce0354-15b1-4126-96c4-7c576dea7fa7)
![image](https://github.com/user-attachments/assets/e3750289-2b9e-411c-ac2e-3646604bf3ec)

Example Map that was not excluded by regex string:
![image](https://github.com/user-attachments/assets/0c8d2a55-51e9-4521-b576-2ccddaabdf25)

**Additional context**
Removed quantity string to see if there were any changes. No change with the alternate regex: "!se a|ra c|re a|n,|xa|wak|wni|ur p"

Seems to be the space+p in  "!ur p" is causing it to not filter out the mod. When tested by itself all maps in map tab including ones containing the mod are highlighted.  "!our" was able to exclude the block mod but "!our P" is not.

**Comment by n1klas4008** [comment]
this should be fixed with e9ff850d5768d54ec4d3d457045297c6d40ba316 thanks for the detailed report.
I had to go and manually add the linebreaks into the mods, I am not sure if I caught all of them so I will leave this issue open for now. The website should now also display those linebreaks as they are visible ingame.

will leave this Issue open for a while to figure out if I caught them all or not but it should be fixed

**Comment by n1klas4008** [comment]
think this is properly fixed, closing this for now
