### ISSUE TITLE
Item Rarity textbox

### ISSUE THREAD

**Issue by guy1195** [n1klas4008/poe-regex#57]
**Is your feature request related to a problem? Please describe.**
No problem, just be nice to have an item rarity +#% support

**Describe the idea/solution you'd like**
New textbox for item rarity #% on t17 maps

**Describe alternatives you've considered**

**Additional context**

**Comment by n1klas4008** [comment]
added with 9091952c037858f3ae161dbb1b51bb7f9e489a0a and finished with #61
